controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_transaction:
    path: /api/transfer
    controller: App\Controller\TransactionController::transferMoney
    methods: POST
